services:
  app_postgre_db:
    image: postgres:17
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - lab4_postgres_data:/var/lib/postgresql/data
      - ./requests/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
#  app_local_storage_level_db:
#    image: leveldb/leveldb:latest
#    volumes:
#      - leveldb_data:/data
#    ports:
#      - "8080:8080"
#    environment:
#      - LEVELDB_PATH=/data

volumes:
  lab4_postgres_data:
#  leveldb_data:
